baseURL = "https://www.lexaeterna.online/"
languageCode = "en-us"
theme = "lexlex"
title = "Lex Æterna"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
publishDir = "docs"
[params]
    description = "Play lex aeterna."
    favicon = "images/favicon.png"
    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Play Lex Æterna."
    [params.meta]
        keywords = "lex aeterna, twitch, jrpg, online, monster brawl"